package com.sos.scheduler.history.classes;

/** \class HistorySeverity
 * 
 * \brief HistorySeverity -
 * 
 * \details
 *
 * \section HistorySeverity.java_intro_sec Introduction
 *
 * \section HistorySeverity.java_samples Some Samples
 *
 * \code .... code goes here ... \endcode
 *
 * <p style="text-align:center">
 * <br />
 * --------------------------------------------------------------------------- <br />
 * APL/Software GmbH - Berlin <br />
 * ##### generated by ClaviusXPress (http://www.sos-berlin.com) ######### <br />
 * ---------------------------------------------------------------------------
 * </p>
 * \author Uwe Risse \version 08.09.2011 \see reference
 *
 * Created on 08.09.2011 13:01:29 */

public class HistorySeverity {

    private String strValue = "";
    private Integer intValue = 0;

    private final String conClassName = "HistorySeverity";

    public HistorySeverity(String strValue) {
        super();
        this.setStrValue(strValue);
    }

    public HistorySeverity(Integer intValue) {
        super();
        this.setIntValue(intValue);
    }

    public String getStrValue() {
        return strValue;
    }

    public void setStrValue(String strValue) {
        this.strValue = strValue;
        if (strValue.equalsIgnoreCase("success")) {
            this.intValue = 0;
        } else {
            this.intValue = 1;
        }
    }

    public Integer getIntValue() {
        return intValue;
    }

    public void setIntValue(Integer intValue) {
        this.intValue = intValue;
        if (intValue == 0) {
            strValue = "success";
        } else {
            strValue = "error";
        }
    }

    public boolean hasValue() {
        return !this.getStrValue().equals("");
    }

    public String getConClassName() {
        return conClassName;
    }

}
