package com.sos.scheduler.db;

import static org.junit.Assert.*;

import java.io.File;
import java.util.List;

import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;

import sos.spooler.Spooler;

/**
* \class SchedulerInstancesDBLayerTest 
* 
* \brief SchedulerInstancesDBLayerTest - 
* 
* \details
*
* \section SchedulerInstancesDBLayerTest.java_intro_sec Introduction
*
* \section SchedulerInstancesDBLayerTest.java_samples Some Samples
*
* \code
*   .... code goes here ...
* \endcode
*
* <p style="text-align:center">
* <br />---------------------------------------------------------------------------
* <br /> APL/Software GmbH - Berlin
* <br />##### generated by ClaviusXPress (http://www.sos-berlin.com) #########
* <br />---------------------------------------------------------------------------
* </p>
* \author Uwe Risse
* \version 03.02.2012
* \see reference
*
* Created on 03.02.2012 10:43:15
 */

public class SchedulerInstancesDBLayerTest {

	@SuppressWarnings("unused")
	private final String	conClassName	= "SchedulerInstancesDBLayerTest";

	public SchedulerInstancesDBLayerTest() {
		//
	}

	@BeforeClass
	public static void setUpBeforeClass() throws Exception {
	}

	@AfterClass
	public static void tearDownAfterClass() throws Exception {
	}

	@Before
	public void setUp() throws Exception {
	}

	@After
	public void tearDown() throws Exception {
	}

	@Test
	public void testSchedulerInstancesDBLayer() {
		fail("Not yet implemented");
	}

	@Test
	public void testDelete() {
		fail("Not yet implemented");
	}

	@Test
	public void testGetSchedulerInstancesList() {
		fail("Not yet implemented");
	}

	@Test
	public void testGetInstanceById() {
		fail("Not yet implemented");
	}

	@Test
	public void testGetFilter() {
		fail("Not yet implemented");
	}

	@Test
	public void testSetFilter() {
		fail("Not yet implemented");
	}

	@Test
	public void testInsertScheduler() {
 	    
		String schedulerId = "myScheduler";
		String hostname = "myHost";
		Integer port = 4711;
		
	
		SchedulerInstancesDBItem schedulerInstancesDbItem = new SchedulerInstancesDBItem();
	    schedulerInstancesDbItem.setHostName(hostname);
	    schedulerInstancesDbItem.setTcpPort(port);
	    schedulerInstancesDbItem.setSchedulerId(schedulerId);
	    schedulerInstancesDbItem.setDbName("myDbname");
	    schedulerInstancesDbItem.setDbHistoryTableName("myDbHistoryTableName");
	    schedulerInstancesDbItem.setDbOrdersTableName("myDbOrdersTableName");
	    schedulerInstancesDbItem.setDbTasksTableName("myDbTasksTableName");
	    schedulerInstancesDbItem.setDbVariablesTableName("myDbVariablesTableName");
	    schedulerInstancesDbItem.setIncludePath("myIncludePath");
	    schedulerInstancesDbItem.setIniPath("myIniPath");
	    schedulerInstancesDbItem.setLogDir("myLogDir");
	    schedulerInstancesDbItem.setParam("myParam");
	    schedulerInstancesDbItem.setIsService(true);
	    schedulerInstancesDbItem.setLiveDirectory("myLiveDirectory");
        schedulerInstancesDbItem.setSupervisorHostName("mySupervisorHostname");
        schedulerInstancesDbItem.setSupervisorTcpPort(4712);

		
		
		
		//Test prepare
		SchedulerInstancesDBLayer schedulerInstancesDBLayer = new SchedulerInstancesDBLayer(new File("R:/nobackup/sos/junit/" + "hibernate_oracle.cfg.xml"));
		schedulerInstancesDBLayer.getFilter().setSchedulerId(schedulerId);
		schedulerInstancesDBLayer.getFilter().setHostname(hostname);
		schedulerInstancesDBLayer.getFilter().setPort(port);
 		schedulerInstancesDBLayer.delete();
 		
 		//Test execute
 		schedulerInstancesDBLayer.insertScheduler(schedulerInstancesDbItem);
		schedulerInstancesDBLayer.commit();		

 		
		//Test control result 
		List  schedulerList  = schedulerInstancesDBLayer.getSchedulerInstancesList();
		assertEquals(1, schedulerList.size());      
   
		 
		
	}
}
