package com.sos.dailyschedule;

import static org.junit.Assert.*;

import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;


import com.sos.scheduler.model.SchedulerObjectFactory;
import com.sos.scheduler.model.commands.JSCmdStartJob;
import com.sos.scheduler.model.objects.Spooler;

 

/**
* \class SchedulerStartJobJUnitTest 
* 
* \brief SchedulerStartJobJUnitTest - 
* 
* \details
*
* \section SchedulerStartJobJUnitTest.java_intro_sec Introduction
*
* \section SchedulerStartJobJUnitTest.java_samples Some Samples
*
* \code
*   .... code goes here ...
* \endcode
*
* <p style="text-align:center">
* <br />---------------------------------------------------------------------------
* <br /> APL/Software GmbH - Berlin
* <br />##### generated by ClaviusXPress (http://www.sos-berlin.com) #########
* <br />---------------------------------------------------------------------------
* </p>
* \author Uwe Risse
* \version 14.10.2011
* \see reference
*
* Created on 14.10.2011 11:24:40
 */

public class SchedulerStartJobJUnitTest {

	@SuppressWarnings("unused")
	private final String	conClassName	= "SchedulerStartJobJUnitTest";

	public SchedulerStartJobJUnitTest() {
		//
	}

	@BeforeClass
	public static void setUpBeforeClass() throws Exception {
	}

	@AfterClass
	public static void tearDownAfterClass() throws Exception {
	}

	@Before
	public void setUp() throws Exception {
	}

	@After
	public void tearDown() throws Exception {
	}

	@Test
	public void testStartJob() {
      SchedulerObjectFactory objSchedulerObjectFactory = new SchedulerObjectFactory("ur", 4000);
      objSchedulerObjectFactory.initMarshaller(Spooler.class);
      JSCmdStartJob objStartJob = objSchedulerObjectFactory.StartJob("job7", false);
    }

	 
	  
}
