package com.sos.jid.dialog.classes;
/**
* \class SosTabJOC 
* 
* \brief SosTabJOC - 
* 
* \details
*
* \section SosTabJOC.java_intro_sec Introduction
*
* \section SosTabJOC.java_samples Some Samples
*
* \code
*   .... code goes here ...
* \endcode
*
* <p style="text-align:center">
* <br />---------------------------------------------------------------------------
* <br /> APL/Software GmbH - Berlin
* <br />##### generated by ClaviusXPress (http://www.sos-berlin.com) #########
* <br />---------------------------------------------------------------------------
* </p>
* \author Uwe Risse
* \version 25.01.2012
* \see reference
*
* Created on 25.01.2012 11:47:41
 */
import org.eclipse.swt.SWT;

import org.eclipse.swt.custom.CTabFolder;
import org.eclipse.swt.custom.CTabItem;

import org.eclipse.swt.layout.GridLayout;
import org.eclipse.swt.widgets.Composite;

import com.sos.dialog.BrowserViewForm;
import com.sos.dialog.classes.SOSUrl;

public class SosTabJOC extends CTabItem {
	private Composite	composite;
	private GridLayout	layout;

	public SosTabJOC( CTabFolder parent, SOSUrl url) {
		super(parent, SWT.NONE);
        this.setData(url);
 		composite = new Composite(parent, SWT.NONE);
		layout = new GridLayout(2, false);
		composite.setLayout(layout);
		if (url != null) {
		   BrowserViewForm b = new BrowserViewForm(composite, SWT.NONE, url);
           setText(url.getUrlCaption());
		}
		composite.layout();
		this.setControl(composite);
	}
}
