package com.sos.dailyschedule.db;

import static org.junit.Assert.assertEquals;

import java.io.File;
import java.util.List;

import org.hibernate.Query;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;

import com.sos.dailyschedule.job.CreateDailyScheduleOptions;

/**
* \class Calendar2DBTest 
* 
* \brief Calendar2DBTest - 
* 
* \details
*
* \section Calendar2DBTest.java_intro_sec Introduction
*
* \section Calendar2DBTest.java_samples Some Samples
*
* \code
*   .... code goes here ...
* \endcode
*
* <p style="text-align:center">
* <br />---------------------------------------------------------------------------
* <br /> APL/Software GmbH - Berlin
* <br />##### generated by ClaviusXPress (http://www.sos-berlin.com) #########
* <br />---------------------------------------------------------------------------
* </p>
* \author Uwe Risse
* \version 06.10.2011
* \see reference
*
* Created on 06.10.2011 17:39:33
 */

public class Calendar2DBTest {

	@SuppressWarnings("unused")
	private final String	conClassName	= "Calendar2DBTest";
    private CreateDailyScheduleOptions objOptions; 
    
    private final String configurationFilename="R:/nobackup/junittests/hibernate/hibernate.cfg.xml";
    private File configurationFile;

	public Calendar2DBTest() {
		//
	}

	@BeforeClass
	public static void setUpBeforeClass() throws Exception {
	}

	@AfterClass
	public static void tearDownAfterClass() throws Exception {
	}

	@Before
	public void setUp() throws Exception {
        configurationFile = new File(configurationFilename);
        System.out.println(configurationFile.getCanonicalPath());
		objOptions = new CreateDailyScheduleOptions();
		objOptions.scheduler_port.value(4210);
		objOptions.SchedulerHostName.Value("8of9");
		objOptions.dayOffset.value(0);
	}

	@After
	public void tearDown() throws Exception {
	}
	
	@Test
	public void testCalendar2DB() throws Exception {
		Calendar2DB calendar2Db = new Calendar2DB(configurationFile);

//		try {
			calendar2Db.setOptions(objOptions);

			calendar2Db.store();

			DailyScheduleDBLayer d = new DailyScheduleDBLayer(configurationFile);
			d.beginTransaction();

			Query query = d.createQuery(" from DailyScheduleDBItem where job like :test");
			query.setParameter("test", "/sos/dailyschedule/CreateDaysSchedule");
			List calendarList = query.list();

			for (int i = 0; i < calendarList.size(); i++) {
				DailyScheduleDBItem calendarItem = (DailyScheduleDBItem) calendarList.get(i);
//				System.out.println("History: " + calendarItem.getJob());
				if (i == 0) {
					assertEquals("/sos/dailyschedule/CreateDaysSchedule", calendarItem.getJob());
					break;
				}
			}

			d.commit();
//		}
//		catch (Exception e) {
//			e.printStackTrace();
//		}
	}
	 	
	

	@Test
	public void testDelete() throws Exception {
	    Calendar2DB calendar2Db = new Calendar2DB(configurationFile);
	    
	    calendar2Db.setOptions(objOptions);
 
	    calendar2Db.delete();
 
	    DailyScheduleDBLayer d = new DailyScheduleDBLayer(configurationFile);
		d.beginTransaction();
		
 		Query query=d.createQuery( " from DailyScheduleDBItem where schedulePlanned >=:from and schedulePlanned <= :to");
		query.setDate("from", calendar2Db.getFrom());
		query.setDate("to", calendar2Db.getTo());

        List calendarList=query.list();
        assertEquals(calendarList.size(),0);		
		d.commit();
 	}
}


