package com.sos.dailyschedule.db;

 
import java.io.File;
import java.util.Date;

import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;

import com.sos.dailyschedule.job.CheckDailyScheduleOptions;

/**
* \class DaysScheduleAdjustmentTest 
* 
* \brief DaysScheduleAdjustmentTest - 
* 
* \details
*
* \section DaysScheduleAdjustmentTest.java_intro_sec Introduction
*
* \section DaysScheduleAdjustmentTest.java_samples Some Samples
*
* \code
*   .... code goes here ...
* \endcode
*
* <p style="text-align:center">
* <br />---------------------------------------------------------------------------
* <br /> APL/Software GmbH - Berlin
* <br />##### generated by ClaviusXPress (http://www.sos-berlin.com) #########
* <br />---------------------------------------------------------------------------
* </p>
* \author Uwe Risse
* \version 07.10.2011
* \see reference
*
* Created on 07.10.2011 10:38:57
 */

public class DailyScheduleAdjustmentTest {

	@SuppressWarnings("unused")
	private final String	conClassName	= "DaysScheduleAdjustmentTest";
    private final String configurationFilename="R:/nobackup/junittests/hibernate/hibernate.cfg.xml";
    private File configurationFile;


	public DailyScheduleAdjustmentTest() {
		//
	}

	@BeforeClass
	public static void setUpBeforeClass() throws Exception {
	}

	@AfterClass
	public static void tearDownAfterClass() throws Exception {
	}

	@Before
	public void setUp() throws Exception {
        configurationFile = new File(configurationFilename);

	}

	@After
	public void tearDown() throws Exception {
	}


	@Test
	public void testAdjustWithHistory() throws Exception {
		DailyScheduleAdjustment dailyScheduleAdjustment = new DailyScheduleAdjustment(configurationFile);
		
        CheckDailyScheduleOptions	objOptions = new CheckDailyScheduleOptions();

        dailyScheduleAdjustment.setTo(new Date());

		dailyScheduleAdjustment.setOptions(objOptions);
		dailyScheduleAdjustment.adjustWithHistory();
	}

}
